# Header
menu:
  首页: /
  相册: /gallery
  活动: /stories
  新闻: /archives
  关于: /about

# Content
excerpt_link: 阅读全文

# MIIT ICP/IP/DOMAIN
beian: 
  enable: true
  number: 苏ICP备15023694号-3
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /images/favicon.ico
webclip: /images/webclip
brand:   /images/brand.svg

# Jumbotron video & Hero image & Swiper
## Jumbotron video
video: 
  overlay: false
  path: /images/movie/
## Hero image
hero: 
  image: /images/banner/banner.jpg
## Swiper
## https://github.com/nolimits4web/swiper
swiper: 
  enable: false

# Toc
## https://github.com/tscanlin/tocbot
toc: true

# Slogan
slogan: 
  primary: T 技术沙龙
  secondary: 专注开发者技术交流的线上 & 线下沙龙
  archives: 汇聚热点话题 打造创新思路
  pages: 记录沙龙活动 保留美好回忆
  posts: 实践见真知既是最好的解释

# Library
libs:
  feather: /libs/feather/feather.min.js # V4.29.0
  lazysizes: /libs/lazysizes/lazysizes.min.js
  tocbot: /libs/tocbot/tocbot.min.js
  swiper: 
    css: /libs/swiper/swiper-bundle.min.css
    js:  /libs/swiper/swiper-bundle.min.js